---
title: 'Web Scraping Twitter for #machinelearningflashcards'
layout: post
tags: [rstats, r, image-processing, machine-learning]
author: "Jasmine Dumas"
output: 
  html_document: 
    self_contained: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```

```{r}
library("rtweet")
library("dplyr")
library("magick")
library("httr")
library("stringr")
```

- Get tweets for the hastag and only curated for Chris Albon's tweets: 
```{r}
ml_tweets <- search_tweets("#machinelearningflashcards", n = 500, include_rts = FALSE) %>% filter(screen_name == 'chrisalbon')
```

- Get text within the tweet to add to the file name by removing the hashtag and url link: 
```{r}
ml_tweets$clean_text <- ml_tweets$text
ml_tweets$clean_text <- str_replace(ml_tweets$clean_text,"#[a-zA-Z0-9]{1,}", "")

ml_tweets$clean_text <- str_replace(ml_tweets$clean_text, " ?(f|ht)(tp)(s?)(://)(.*)[.|/](.*)", "")

ml_tweets$clean_text <- str_replace(ml_tweets$clean_text, "[[:punct:]]", "")
```


- Download images of the flashcards from `media_url` column:
```{r}
save_image <- function(df){
  for (i in c(1:nrow(df))){
    image <- try(image_read(df$media_url[i]), silent = F)
  if(class(image)[1] != "try-error"){
    image %>%
      image_scale("1200x700") %>%
      image_write(paste0("data/", ml_tweets$clean_text[i],".jpg"))
  }
 
  }
   cat("Function complete...\n")
}
```

- Apply a function to each element of a vector for saving:
```{r}
save_image(ml_tweets)
```

